### ISSUE TITLE
CONFIG NOTE: OpenWRT + Chromecast

### ISSUE THREAD

**Issue by oliverfoster** [nigelb/Static-UPnP#2]
I had five issues with the setup and config.

0. I had to install python with "opkg install python"

1. I had to manually download, unpack, move to my router (using sftp) and install (using ssh) https://pypi.python.org/simple/schedule/ and https://pypi.python.org/simple/pyip/ with "python setup.py install"

2. To have it run automatically is used this in me "/etc/rc.local" file:
"python /root/Static-UPnP/static_upnp/static.py --config-dir /root/Static-UPnP/examples/Chromecast/ &"

3. The group in OpenWRT is "nogroup" not "nobody". change here https://github.com/nigelb/Static-UPnP/blob/master/examples/Chromecast/StaticUPnP_Permissions.py#L19

4. The router needs to accept 239.255.255.250 traffic. So I had to add a static route to "239.255.255.250" mask "255.255.255.255" on the interface without the Chromecast.

I hope this helps someone else figure it all out.

You can also replace this line https://github.com/nigelb/Static-UPnP/blob/master/examples/Chromecast/StaticUPnP_StaticServices.py#L61 with the static ip address of your chromecast if you can't set dns name resolution for "Chromecast"

It works perfectly though. I have a chromecast available on two separate subnets.

**Comment by nigelb** [comment]
Hi,

Thanks for the feedback. I have made some changes [in a new branch](/nigelb/Static-UPnP/tree/multicast_update) to address the following issues: 

In regardsto item 3, I was not actually dropping permissions, that code was left over from an experiment when trying to get everything working, however, it is now functions as expected and dropes permissions when launched as root. Note that these setting are now in the [StaticUPnP_Settings.py](/nigelb/Static-UPnP/blob/multicast_update/examples/Chromecast/StaticUPnP_Settings.py) file

The 4th issue may have been due to not having conducted a multicast membership request for each interface, which now happens in this branch. However, In this fix I have used the netifaces package, which may be problematic in your deployment. Hopefully you can install it with your system package manager (opkg), for me the package name was `python-netifaces` but I am not using an openwrt router so I do not know what packages are available.

The other thing to note is that the configuration files have changed so you will need to update them as well.

**Comment by nigelb** [comment]
I have added a new configuration `ip_addresses` item to [StaticUPnP_Settings.py](https://github.com/nigelb/Static-UPnP/blob/multicast_update/examples/Chromecast/StaticUPnP_Settings.py#L29). If you populate this list with the IP addresses of the interface you want to listen on, then the netifaces dependency is not required.

I have also merged the new branch into master.

**Comment by oliverfoster** [comment]
Awesome, thanks! I'll give this a try in the next few days :D
